# Generated by Django 4.2.16 on 2026-04-02 09:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('background_color', models.CharField(default='#F0F0F0', help_text='Couleur hex, ex: #FF5733', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.PositiveIntegerField(help_text='Prix en FCFA', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit', models.CharField(choices=[('kg', 'Kilogramme'), ('g', 'Gramme'), ('l', 'Litre'), ('pcs', 'Pièce(s)'), ('lot', 'Lot')], default='pcs', max_length=10)),
                ('origin', models.CharField(blank=True, help_text='Origine du produit (ex: Local, Importé)', max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('ingredients', models.TextField(blank=True, help_text='Ingrédients séparés par virgule')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Produit phare')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Profitez de nos offres spéciales !', max_length=200)),
                ('subtitle', models.CharField(help_text='Ex: 30% de réduction sur les produits sélectionnés', max_length=300)),
                ('validity_text', models.CharField(help_text="Ex: Valable jusqu'au 30 septembre", max_length=200)),
                ('discount_percent', models.PositiveIntegerField(default=0, help_text='Pourcentage de réduction (0 si non applicable)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='products.product')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Titre affiché sur la bannière (ex: Légumes frais du jour)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='products.product')),
            ],
            options={
                'verbose_name': 'Produit phare',
                'verbose_name_plural': 'Produits phares',
                'ordering': ['order'],
            },
        ),
    ]
